version: "3"
services:
  opencv:
    image: mohaseeb/raspberrypi3-python-opencv:4.1.0
    volumes:
      - ./opencv_app.py:/opencv_app.py 
    environment:
      - CAMERA_URL
    command: python /opencv_app.py 

