version: "2"
services:
  opencv:
    build: .
    volumes:
      - ./tulikivi.py:/tulikivi.py
    networks:
      - host
    environment:
      - CAMERA_URL
    command: python /tulikivi.py

networks:
  host:
